name: Build and Release Agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            target: x86_64-unknown-linux-gnu
            binary_name: agent
            asset_name: agent-linux-x64
          - os: windows-latest
            platform: windows-x64
            target: x86_64-pc-windows-msvc
            binary_name: agent.exe
            asset_name: agent-windows-x64.exe
          - os: macos-latest
            platform: macos-x64
            target: x86_64-apple-darwin
            binary_name: agent
            asset_name: agent-macos-x64
          - os: macos-14
            platform: macos-arm64
            target: aarch64-apple-darwin
            binary_name: agent
            asset_name: agent-macos-arm64

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --manifest-path rust-core/Cargo.toml -p agent --target ${{ matrix.target }}

    - name: Rename and Move Binary
      shell: bash
      run: |
        cp rust-core/target/${{ matrix.target }}/release/${{ matrix.binary_name }} ${{ matrix.asset_name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}
